on: [push, pull_request]
name: Test
jobs:
  unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
       make actions-test
       bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
  race-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: RACE=1 make test
  memfs-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: MEMFS_TEST=1 make test
  go1-16-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  go1-17-unit-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  macos-unit-test:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test
  build-tools:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: make tools
  build-examples:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x
    - name: Build
      run: |
       git clone https://github.com/lni/dragonboat-example
       cd dragonboat-example
       GOPROXY=direct go get github.com/lni/dragonboat/v4@master
       make
  static-check:
    runs-on: ubuntu-18.04
    steps: 
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: 1.18.x
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Static check
       run:
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash -s -- -b $GOROOT/bin v1.45.2
        make static-check
